### PR TITLE
API documentation

### PR DESCRIPTION
**Pull request by N-Wouda**

### CODE REVIEW

**Comment by N-Wouda** [comment]
@leonlan why does the new notebook stuff fail?

**Comment by leonlan** [comment]
> @leonlan why does the new notebook stuff fail?

I have no idea. You can remove it from the CI and then I’ll look into this tomorrow morning.

**Review by leonlan — APPROVED** [review]

**Comment by leonlan** [comment]
> @leonlan why does the new notebook stuff fail?

Does it something have to do with https://github.com/N-Wouda/PyVRP/issues/113#issuecomment-1446942862?
The CI now passes wihtout any changes. https://github.com/N-Wouda/PyVRP/pull/152 also passes the CI. The assertion that failed was probably due to `solution.cost()` returning an incorrect value.

**Comment by N-Wouda** [comment]
> Does it something have to do with [#113 (comment)](https://github.com/N-Wouda/PyVRP/issues/113#issuecomment-1446942862)? The CI now passes without any changes. #152 also passes the CI. The assertion that failed was probably due to `solution.cost()` returning an incorrect value.

Could well be! I'll add some docs here for the operators as well, and then merge this in. I'm pretty confident the documentation didn't cause the issue :).

**Pull request merged**
