### PR TITLE
Remove PenaltyManager state from LS operators

### PR DESCRIPTION
**Pull request by N-Wouda**
This PR is part of #157 and removes the `PenaltyManager` reference from LS operators.

### CODE REVIEW

**Comment by N-Wouda** [comment]
@leonlan @wouterkool can you have a look? I debated removing the data piece of the state as well, but in the end I figured it wasn't a problem and having it in the operators simplifies the interface a bit. 

Removing `PenaltyManager` seems more pressing. It's now passed in by the local search, as a step up to removing it there as well in favour of a small penalties object.

**Review by leonlan — APPROVED** [review]
LGTM.

**Review by wouterkool — APPROVED** [review]
Nice! One thing to consider in the future is how we make sure we invalidate the SWAP* cache if the penalties change. I think now, in theory, we could change the penalties but have the old SWAP* cache (but this doesn't happen as we always load the individual again after changing penalties).

**Comment by wouterkool** [comment]
@N-Wouda can we merge this?

**Pull request merged**
